# Missing values: Detection and Exploration

## 1. Import Libraries

In [1]:
import janitor
import matplotlib.pyplot as plt
import missingno
import numpy as np
import pandas as pd
import pyreadr
import seaborn as sns
import session_info
import upsetplot

/home/milo/24-Faltantes-Detección-Exploración/env/lib/python3.10/site-packages/upsetplot/data.py:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion

## 2. Load Dataset

In [7]:
oceanbuoys_df = pyreadr.read_r('../data/oceanbuoys.rda').get('oceanbuoys')
oceanbuoys_df

,hourly_counts,date_time,year,month,month_day,week_day,hour,sensor_id,sensor_name
0,883,2016-01-01 00:00:00,2016,January,1,Friday,0,2,Bourke Street Mall (South)
1,597,2016-01-01 01:00:00,2016,January,1,Friday,1,2,Bourke Street Mall (South)
2,294,2016-01-01 02:00:00,2016,January,1,Friday,2,2,Bourke Street Mall (South)
3,183,2016-01-01 03:00:00,2016,January,1,Friday,3,2,Bourke Street Mall (South)
4,118,2016-01-01 04:00:00,2016,January,1,Friday,4,2,Bourke Street Mall (South)
...,...,...,...,...,...,...,...,...,...
37695,349,2016-12-31 19:00:00,2016,December,31,Saturday,19,23,Spencer St-Collins St (South)
37696,337,2016-12-31 20:00:00,2016,December,31,Saturday,20,23,Spencer St-Collins St (South)
37697,356,2016-12-31 21:00:00,2016,December,31,Saturday,21,23,Spencer St-Collins St (South)
37698,459,2016-12-31 22:00:00,2016,December,31,Saturday,22,23,Spencer St-Collins St (South)
37699,422,2016-12-31 23:00:00,2016,December,31,Saturday,23,23,Spencer St-Collins St (South)